# Generated by Django 5.1.6 on 2025-04-15 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('revelation_type', models.CharField(choices=[('Meccan', 'Meccan'), ('Medinan', 'Medinan')], default='Meccan', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ayat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('text', models.TextField()),
                ('translation', models.TextField(blank=True, null=True)),
                ('transliteration', models.TextField(blank=True, null=True)),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayats', to='quran.surah')),
            ],
        ),
    ]
