# Generated by Django 5.1.6 on 2025-03-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('ustaz', 'Ustaz'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
